name: Release Go App

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "*.md"
  workflow_dispatch:
    inputs:
      note:
        description: "Notes"
        required: false
        default: "Manual trigger"

# permissions:
#   contents: write

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use PAT with repo scope
          # GITHUB_TOKEN: ${{ secrets.GO_RELEASER }} 
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: go-app
          path: dist/*